---
- name: Add SSH key to authorized_keys
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ensure SSH key is present in authorized_keys for almalinux user
      ansible.builtin.authorized_key:
        user: almalinux
        state: present
        key: "{{ lookup('file', '/home/almalinux/.ssh/id_rsa.pub') }}"

#- import_playbook: update.yaml
- import_playbook: local.yaml
#- import_playbook: reboot.yaml
- import_playbook: tools.yaml
- import_playbook: install_pyspark.yaml
- import_playbook: second-disk.yaml
- import_playbook: setup_cluster.yaml
#- import-playbook: setup_data.yaml
