---
- name: Install Spark and dependencies
  hosts: all
  become: true
  tasks:
    - name: Ensure tar and gzip are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - tar
        - gzip
     # when: ansible_facts['os_family'] == "RedHat"

    - name: Download Spark
      get_url:
        url: https://downloads.apache.org/spark/spark-3.5.4/spark-3.5.4-bin-hadoop3.tgz
        dest: /tmp/spark-3.5.4-bin-hadoop3.tgz

    - name: Extract Spark
      unarchive:
        src: /tmp/spark-3.5.4-bin-hadoop3.tgz
        dest: /opt/
        remote_src: yes

    - name: Create symlink
      file:
        src: /opt/spark-3.5.4-bin-hadoop3
        dest: /opt/spark
        state: link

    - name: Set SPARK_HOME in environment variables
      lineinfile:
        path: /etc/environment
        line: 'SPARK_HOME=/opt/spark'
        state: present

    - name: Add Spark to PATH
      lineinfile:
        path: /etc/environment
        line: 'PATH=$PATH:/opt/spark/bin'
        state: present
