- name: Update packages and install minimum requirements.
  hosts: all
  become: true
  become_user: root
  vars:
    python_packages:
      - einops
      - matplotlib
      - natsort
      - networkx
      - "numpy<2.0"
      - rotary_embedding_torch
      - scipy
      - setuptools
      - "torch==2.0.1"
  tasks:
    - name: Install quality of life tools
      ansible.builtin.dnf:
        name:
          - vim
          - emacs
          - nano
          - screen
          - tmux
          - net-tools
          - bind-utils
          - htop
          - git
          - ansible
          - make
          - unzip
          - wget
          - links
        state: latest

    - name: Install Python 3
      ansible.builtin.dnf:
        name:
          - python3-devel
          - python3-pip
          - python3-virtualenv
        state: latest

    - name: Install compilers
      ansible.builtin.dnf:
        name:
          - g++
          - gfortran
          - openmpi-devel
          - openmpi
          - patch
          - bzip2
          - python3-mpi4py-openmpi
          - make
        state: latest

    - name: Install system dependencies
      ansible.builtin.yum:
        name:
          - java-11-openjdk
        state: present

    - name: Upgrade pip to the latest version
      ansible.builtin.pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install required Python packages
      ansible.builtin.pip:
        name: "{{ python_packages }}"
        state: present
        executable: pip3
      when: inventory_hostname in groups['workers']
