---
- name: Configure NFS storage
  hosts: storage
  become: true

  tasks:
    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Ensure shared directory exists
      file:
        path: /shared/data
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Export shared directory
      lineinfile:
        path: /etc/exports
        line: "/shared/data *(rw,sync,no_root_squash)"
        create: yes

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted
