---
- name: Mount shared directory on workers
  hosts: worker
  become: true

  tasks:
    - name: Install NFS utilities
      apt:
        name: nfs-common
        state: present

    - name: Mount shared directory
      mount:
        path: /shared/data
        src: storage:/shared/data
        fstype: nfs
        opts: defaults
        state: mounted
